use clipboard_rs::{Clipboard, ClipboardContext};
use clipboard_rs::common::RustImage;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::db::ClipEntry;

// Pasteboard types that indicate sensitive/transient content — skip these.
const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

pub fn is_concealed(ctx: &ClipboardContext) -> bool {
    if let Ok(types) = ctx.available_formats() {
        for t in &types {
            if CONCEALED_TYPES.iter().any(|c| t.contains(c)) {
                return true;
            }
        }
    }
    false
}

pub fn read_entry(ctx: &ClipboardContext, capture_images: bool, source_app: Option<String>, images_dir: &std::path::Path) -> Option<ClipEntry> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64;

    // Priority: HTML (with text content) > plain text > image
    // If HTML has no visible text (e.g. browser image copy puts <img> tag only), skip it
    // and fall through to image detection.
    if let Ok(html) = ctx.get_html() {
        if !html.trim().is_empty() && !strip_tags(&html).trim().is_empty() {
            let hash = hex_hash(html.as_bytes());
            return Some(ClipEntry {
                id: 0,
                kind: "html".to_string(),
                content: Some(html),
                image_path: None,
                source_app,
                hash,
                pinned: false,
                created_at: now,
            });
        }
    }

    if let Ok(text) = ctx.get_text() {
        if !text.trim().is_empty() {
            let hash = hex_hash(text.as_bytes());
            return Some(ClipEntry {
                id: 0,
                kind: "text".to_string(),
                content: Some(text),
                image_path: None,
                source_app,
                hash,
                pinned: false,
                created_at: now,
            });
        }
    }

    if capture_images {
        if let Ok(img) = ctx.get_image() {
            if let Ok(buf) = img.to_png() {
                let bytes = buf.get_bytes();
                if !bytes.is_empty() {
                    let hash = hex_hash(bytes);
                    let filename = format!("{}.png", hash);
                    let image_path = images_dir.join(&filename);
                    if let Err(e) = std::fs::write(&image_path, bytes) {
                        eprintln!("Failed to write image: {}", e);
                        return None;
                    }
                    return Some(ClipEntry {
                        id: 0,
                        kind: "image".to_string(),
                        content: None,
                        image_path: Some(image_path.to_string_lossy().into_owned()),
                        source_app,
                        hash,
                        pinned: false,
                        created_at: now,
                    });
                }
            }
        }
    }

    None
}

fn strip_tags(html: &str) -> String {
    let mut out = String::new();
    let mut in_tag = false;
    for c in html.chars() {
        match c {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(c),
            _ => {}
        }
    }
    out
}

fn hex_hash(data: &[u8]) -> String {
    blake3::hash(data).to_hex().to_string()
}

#[cfg(target_os = "macos")]
pub fn frontmost_app() -> Option<String> {
    use objc2_app_kit::NSWorkspace;
    unsafe {
        let ws = NSWorkspace::sharedWorkspace();
        ws.frontmostApplication()
            .and_then(|app| app.localizedName())
            .map(|name| name.to_string())
    }
}

#[cfg(not(target_os = "macos"))]
pub fn frontmost_app() -> Option<String> {
    None
}
